name: Publish Status
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - name: Build Documentation
      run: npm run build
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: public